Support for yaml config file
This add a -c command argument to pass a config file path. This allow
the user to specify multiple compilation targets. A default value
"publicodes.yaml" is used when absent. If both inputs files, and
config file are given by the user, the config file is ignored.

Currently the watch mode is not supported when building multiple
targets. An error message is displayed to the user for now.

The yaml format is simple, and specify the build targets:

	targets:
	  - output: test.js.local
	    inputs:
	      - test.publicodes.local
	    type: js
	    default_to_public: false

All fields are checked, and a corresponding error message is build to
the notice the user on invalid format. Ex:

Error: Parsing config: "targets" field error: "inputs" field error: Expected a string value